### ISSUE TITLE
How can we apply Causal balancing to a new dataset such as NICO?

### ISSUE THREAD

**Issue by Feeeeeel** [WANGXinyiLinda/causal-balancing-for-domain-generalization#1]
I want to use your algorithm on NICO, but it seems to require records.json

What do I need to do?

**Comment by WANGXinyiLinda** [comment]
Not sure where you need records.json. But you should be able to add a dataset by implementing a subclass of `MultipleDomainDataset` in `domainbed/datasets.py` to load your dataset. You will be able to use that dataset by providing the dataset class name to the `--dataset` argument. The core algorithm of causal matching is in `domainbed/match`. You can also transfer the algorithm to your own codebase.

**Comment by Feeeeeel** [comment]
ok, thank you for your reply
