### ISSUE TITLE
TypeError: wrap_datasets() got an unexpected keyword argument 'match_env'

### ISSUE THREAD

**Issue by Feeeeeel** [WANGXinyiLinda/causal-balancing-for-domain-generalization#2]
I am trying to reproduction results, but when the 10000 steps training finished, it got:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/disk2/ywh/CB_DG/domainbed/match/train.py", line 301, in <module>
    train_match, _ = utils.wrap_datasets(train_datasets, algorithm, 
TypeError: wrap_datasets() got an unexpected keyword argument 'match_env'

I check match/train.py and match/utils.py and find difference keyword between these codes:
match/train.py line301:
        train_match, _ = utils.wrap_datasets(train_datasets, algorithm, 
                            dataset.num_classes, batch_size=hparams['batch_size'], 
                            match_env=True, dist_func=hparams['distance_func'], 
                            device=device, use_raw_index=True, threshold=False,
                            topk=hparams['topk'], 
                            use_propensity_score=True)
                            
match/utils.py line254:
def wrap_datasets(in_splits, matcher, num_classes, batch_size=32,
                dist_func='l2', device="cuda", verbose=True, use_raw_index=False, 
                threshold=False, topk=1, num_cf=1)

**Comment by WANGXinyiLinda** [comment]
I apologize for the bug. There was some inconsistency when I cleaned the code. I just deleted the redundant arguments and it should be good now.

**Comment by Feeeeeel** [comment]
By the way, in match/hparams_registry.py line 75, it should be added 'return hparams'.
Then the code can run successfully, thanks!

**Comment by WANGXinyiLinda** [comment]
Thank you for pointing this out. Fixed the bug. Closing the issue now.
