### ISSUE TITLE
ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by Feeeeeel** [WANGXinyiLinda/causal-balancing-for-domain-generalization#4]
A new bug appear after training phrase. The bug occurs when 'num_cf' is set to both 2 and 4.

Original Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk2/ywh/CB_DG/domainbed/match/utils.py", line 196, in __getitem__
    chosen_classes = random.sample(list(range(len(self.cf_ids[0]))), self.num_cf)
  File "/usr/local/anaconda3/envs/EK/lib/python3.9/random.py", line 449, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by Feeeeeel** [comment]
This is the x.sh setting:
CUDA_VISIBLE_DEVICES=7 python -m domainbed.scripts.sweep_selected launch --data_dir /disk1/zl/DATA --selected_records sweep_7df6f06/chosen_records.json --output_dir output_CMNIST --command_launcher local --algorithms CORAL --match_algorithms CVAE --datasets ColoredMNIST --num_cf 2 --use_gpu --single_test_envs --skip_confirmation

**Comment by Feeeeeel** [comment]
It seems that ’num_cf‘ only can be set to 1 when I train on ColoredMNIST?
I would like to know how ’num_cf‘ is configured, thanks!

**Comment by WANGXinyiLinda** [comment]
num_cf is the number of matched examples, or $a$ in algorithm 1 in the paper. Since the matched examples must have different labels than the original example, $a$ < num classes. And since coloredMNIST is a binary classification, $a$ can only be 1.

**Comment by WANGXinyiLinda** [comment]
Closing this issue for now. Please feel free to open a new issue if you have more questions.
